[alpaca]
key = "PK99OKUJAAI9KIINMT9G"
secret = "isFedDOxxFjl5KWuzSnPoe8Zb7aHMUYig4VDsuyI"
base_url = "https://paper-api.alpaca.markets"

#[yfinance]
#key = "your_yfinance_key"

#[binance]
#key = "your_binance_api_key"
#secret = "your_binance_api_secret"
